version: 2
jobs:
  build:
    branches:
        only:
          - develop
    docker:
      - image: node:11
    steps:
      - checkout
      - run:
          name: Install dependencies 
          command: npm install
      - run: 
          name: Audit dependencies
          command: npm audit
      - run: 
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths: [node_modules]
  test:
    docker:
      - image: node:11
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: 
          name: Run linter
          command: npm run lint
      - run: 
          name: Run Test
          command: npm run test
  
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build